/*
 * This file was automatically generated by `gen_opcodes.py`
 * DO NOT EDIT MANUALLY
 */

package opcode

enum Operand:
  case U8(val value: Short)
  case U16(val value: Int)
  case S16(val value: Short)

enum Opcode:
  case OpRet
  case OpConst
  case OpNull
  case OpAddI64
  case OpSubI64
  case OpMulI64
  case OpDivI64
  case OpLeqI64
  case OpLtI64
  case OpGeqI64
  case OpGtI64
  case OpNegI64
  case OpAddF64
  case OpSubF64
  case OpMulF64
  case OpDivF64
  case OpLeqF64
  case OpLtF64
  case OpGeqF64
  case OpGtF64
  case OpPrint
  case OpConcat
  case OpPrintStr
  case OpEq
