/*
 * This file was automatically generated by `gen_opcodes.py`
 * DO NOT EDIT MANUALLY
 */

use serde::{Deserialize, Serialize};
use std::error::Error;

#[repr(u8)]
#[derive(Debug, Eq, PartialEq, Serialize, Deserialize, Copy, Clone)]
pub enum Op {
    OpRet = 0,
    OpConst = 1,
    OpNull = 2,
    OpAddI64 = 3,
    OpSubI64 = 4,
    OpMulI64 = 5,
    OpDivI64 = 6,
    OpLeqI64 = 7,
    OpLtI64 = 8,
    OpGeqI64 = 9,
    OpGtI64 = 10,
    OpNegI64 = 11,
    OpAddF64 = 12,
    OpSubF64 = 13,
    OpMulF64 = 14,
    OpDivF64 = 15,
    OpLeqF64 = 16,
    OpLtF64 = 17,
    OpGeqF64 = 18,
    OpGtF64 = 19,
    OpJump = 20,
    OpJumpTrue = 21,
    OpJumpFalse = 22,
    OpPrint = 23,
    OpConcat = 24,
    OpPrintStr = 25,
    OpEq = 26,
}
use Op::*;

impl TryFrom<u8> for Op {
    type Error = Box<dyn Error>;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Ok(match value {
            0 => OpRet,
            1 => OpConst,
            2 => OpNull,
            3 => OpAddI64,
            4 => OpSubI64,
            5 => OpMulI64,
            6 => OpDivI64,
            7 => OpLeqI64,
            8 => OpLtI64,
            9 => OpGeqI64,
            10 => OpGtI64,
            11 => OpNegI64,
            12 => OpAddF64,
            13 => OpSubF64,
            14 => OpMulF64,
            15 => OpDivF64,
            16 => OpLeqF64,
            17 => OpLtF64,
            18 => OpGeqF64,
            19 => OpGtF64,
            20 => OpJump,
            21 => OpJumpTrue,
            22 => OpJumpFalse,
            23 => OpPrint,
            24 => OpConcat,
            25 => OpPrintStr,
            26 => OpEq,
            x => return Err(format!("Unknown opcode: {}", x).into()),
        })
    }
}
