/*
 * This file was automatically generated by `gen_opcodes.py`
 * DO NOT EDIT MANUALLY
 */

use serde::{Deserialize, Serialize};
use std::error::Error;

#[repr(u8)]
#[derive(Debug, Eq, PartialEq, Serialize, Deserialize, Copy, Clone)]
pub enum Op {
    OpRet = 0,
    OpConst = 1,
    OpNull = 2,
    OpPop = 3,
    OpLoad = 4,
    OpStore = 5,
    OpAddI64 = 6,
    OpSubI64 = 7,
    OpMulI64 = 8,
    OpDivI64 = 9,
    OpLeqI64 = 10,
    OpLtI64 = 11,
    OpGeqI64 = 12,
    OpGtI64 = 13,
    OpNegI64 = 14,
    OpAddF64 = 15,
    OpSubF64 = 16,
    OpMulF64 = 17,
    OpDivF64 = 18,
    OpLeqF64 = 19,
    OpLtF64 = 20,
    OpGeqF64 = 21,
    OpGtF64 = 22,
    OpJump = 23,
    OpJumpTrue = 24,
    OpJumpFalse = 25,
    OpPrint = 26,
    OpConcat = 27,
    OpPrintStr = 28,
    OpEq = 29,
}
use Op::*;

impl TryFrom<u8> for Op {
    type Error = Box<dyn Error>;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Ok(match value {
            0 => OpRet,
            1 => OpConst,
            2 => OpNull,
            3 => OpPop,
            4 => OpLoad,
            5 => OpStore,
            6 => OpAddI64,
            7 => OpSubI64,
            8 => OpMulI64,
            9 => OpDivI64,
            10 => OpLeqI64,
            11 => OpLtI64,
            12 => OpGeqI64,
            13 => OpGtI64,
            14 => OpNegI64,
            15 => OpAddF64,
            16 => OpSubF64,
            17 => OpMulF64,
            18 => OpDivF64,
            19 => OpLeqF64,
            20 => OpLtF64,
            21 => OpGeqF64,
            22 => OpGtF64,
            23 => OpJump,
            24 => OpJumpTrue,
            25 => OpJumpFalse,
            26 => OpPrint,
            27 => OpConcat,
            28 => OpPrintStr,
            29 => OpEq,
            x => return Err(format!("Unknown opcode: {}", x).into()),
        })
    }
}
